/**
 * Maps a raw inbox/letterbox API entry to the flat shape used by the grid.
 */
export const mapInboxEntry = (item) => {
  const props = item?.content ? (item?.content?.properties ?? {}) : (item ?? {});
  const {
    id,
    r_object_id,
    decision,
    uid_number,
    status,
    entry_type,
    mode_of_receipt,
    letter_subject,
    type_category,
    languages,
    secrecy,
    priority,
    inward_ref_number,
    address_of_sender,
    state_of_sender,
    file_number,
    nature_of_correspondence,
    source_vertical,
    vertical_head_display_name,
    due_date,
    completion_date,
    received_from,
    selected_region,
    vertical_head,
    vertical_users,
    endorsed_to,
    is_endorsed_letter,
    selected_cgm_group,
    region,
    group_uid,
    initiator,
    i_folder_id,
    user_comments,
    login_office_type,
    login_region,
    case_number,
    inward_vertical,
    draft_office_type,
    draft_selected_recipients,
    ddm_vertical,
    is_ddm,
  } = props;

  return {
    id: id || r_object_id,
    screenName: "",
    decision: decision,
    digidak_uid: uid_number || "-",
    status: status || "-",
    selected_region: selected_region || "-",
    entry_type: entry_type || "-",
    modeOfReceipt: mode_of_receipt || "-",
    subject: letter_subject || "-",
    category: type_category || "-",
    language: languages || "-",
    secrecy: secrecy || "-",
    priority: priority || "-",
    receivedFrom: received_from || "-",
    referenceNumber: inward_ref_number || "-",
    senderAddress: address_of_sender || "-",
    stateOfSender: state_of_sender || "-",
    fileNumber: file_number || "-",
    natureOfCorrespondence: nature_of_correspondence || "-",
    src_vertical: source_vertical || "-",
    vertical_head_display_name: vertical_head_display_name || "-",
    // vertical_head_short_name: vertical_head_display_name ? vertical_head_display_name.replace(/-[^-]*$/, "").trim() : "-",
    vertical_head_short_name: vertical_head_display_name ? vertical_head_display_name.split("-").slice(0, -1).join("-").trim() : "-",
    date: completion_date || "-",
    due_date: due_date || "-",
    inward_ref_date: inward_ref_number || "-",
    from: entry_type === "Internal" ? login_region : received_from,
    src_vertical_group_name: vertical_head || "-",
    assign_to: Array.isArray(vertical_users) ? vertical_users || "-" : "-",
    endorsed_to: endorsed_to || "-",
    is_endorsed_letter: is_endorsed_letter || "-",
    selected_cgm_group: selected_cgm_group || "",
    vertical_head: vertical_head || "",
    selectedHOROTE: region?.split("-")[0] || "",
    group_uid: group_uid || "",
    initiator: initiator || "",
    i_folder_id: i_folder_id || [],
    user_comments: user_comments || "",
    login_office_type: login_office_type || "",
    login_region: login_region || "",
    case_number: case_number || "",
    inward_vertical: inward_vertical || "",
    draft_office_type: draft_office_type || [],
    draft_selected_recipients: draft_selected_recipients || [],
    ddm_vertical: ddm_vertical || "",
    is_ddm: is_ddm,
  };
};
